### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by macliems** [angular-university/angular-firebase-app#1]
Although the app seems to work fine, I do get this build error:

````
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/macliems/Desktop/ng2-firebase/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/macliems/Desktop/ng2-firebase/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/macliems/Desktop/ng2-firebase/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/macliems/Desktop/ng2-firebase/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main
````

**Comment by jhades** [comment]
Its now fixed, thanks for reporting. Please update the repo, and by running npm install and ng serve it all should work again. KR Vasco
